export interface VineyardI {
  id: number;
  name: string;
  description: string;
  location: string;
  lat: number;
  lng: number;
  img: string;
  score: number;
  slug: string;
}

export const getVineyards = async (): Promise<VineyardI[]> => {
  // Simulated data fetching
  return [
    {
      id: 1,
      name: "Sunny Vineyard",
      description: "A beautiful vineyard with sunny slopes.",
      location: "California",
      lat: 38.297538,
      lng: -122.286865,
      img: "https://example.com/sunny-vineyard.jpg",
      score: 8.5,
      slug: "sunny-vineyard",
    },
    {
      id: 2,
      name: "Mountain Vineyard",
      description: "A vineyard located in the mountains.",
      location: "Colorado",
      lat: 39.550051,
      lng: -105.782067,
      img: "https://example.com/mountain-vineyard.jpg",
      score: 7.8,
      slug: "mountain-vineyard",
    },
    {
      id: 3,
      name: "Coastal Vineyard",
      description: "A vineyard with stunning coastal views.",
      location: "Oregon",
      lat: 43.804133,
      lng: -120.554201,
      img: "https://example.com/coastal-vineyard.jpg",
      score: 9.2,
      slug: "coastal-vineyard",
    },
    {
      id: 4,
      name: "Riverbend Vineyard",
      description: "A vineyard nestled along a scenic riverbend.",
      location: "Washington",
      lat: 47.751076,
      lng: -120.740135,
      img: "https://example.com/riverbend-vineyard.jpg",
      score: 8.0,
      slug: "riverbend-vineyard",
    },
    {
      id: 5,
      name: "Lakeside Vineyard",
      description: "Vines que bordean un lago cristalino.",
      location: "Minnesota",
      lat: 46.7296,
      lng: -94.6859,
      img: "https://example.com/lakeside-vineyard.jpg",
      score: 7.5,
      slug: "lakeside-vineyard",
    },
    {
      id: 6,
      name: "Desert Bloom Vineyard",
      description: "Cultivos resilientes en pleno desierto.",
      location: "Arizona",
      lat: 34.0489,
      lng: -111.0937,
      img: "https://example.com/desert-bloom-vineyard.jpg",
      score: 6.9,
      slug: "desert-bloom-vineyard",
    },
    {
      id: 7,
      name: "Prairie Wind Vineyard",
      description: "Viñedo de planicies con vientos constantes.",
      location: "Kansas",
      lat: 39.0119,
      lng: -98.4842,
      img: "https://example.com/prairie-wind-vineyard.jpg",
      score: 7.0,
      slug: "prairie-wind-vineyard",
    },
    {
      id: 8,
      name: "Harbor View Vineyard",
      description: "Vista directa al puerto y al océano.",
      location: "Maine",
      lat: 45.2538,
      lng: -69.4455,
      img: "https://example.com/harbor-view-vineyard.jpg",
      score: 8.3,
      slug: "harbor-view-vineyard",
    },
    {
      id: 9,
      name: "Casablanca Reserva",
      description: "Clima frío ideal para blancos elegantes.",
      location: "Casablanca, Chile",
      lat: -33.3203,
      lng: -71.398,
      img: "https://example.com/casablanca-reserva.jpg",
      score: 9.0,
      slug: "casablanca-reserva",
    },
    {
      id: 10,
      name: "Maipo Heritage",
      description: "Cabernets históricos al pie de la cordillera.",
      location: "Valle del Maipo, Chile",
      lat: -33.742,
      lng: -70.727,
      img: "https://example.com/maipo-heritage.jpg",
      score: 8.7,
      slug: "maipo-heritage",
    },
    {
      id: 11,
      name: "Colchagua Estate",
      description: "Tintos intensos de clima cálido.",
      location: "Valle de Colchagua, Chile",
      lat: -34.58,
      lng: -71.36,
      img: "https://example.com/colchagua-estate.jpg",
      score: 9.1,
      slug: "colchagua-estate",
    },
    {
      id: 12,
      name: "Elqui Heights",
      description: "Viñedo de altura con cielos despejados.",
      location: "Valle del Elqui, Chile",
      lat: -29.9182,
      lng: -70.9592,
      img: "https://example.com/elqui-heights.jpg",
      score: 8.4,
      slug: "elqui-heights",
    },
    {
      id: 13,
      name: "Itata Heritage",
      description: "Parras centenarias junto al Pacífico.",
      location: "Valle del Itata, Chile",
      lat: -36.54,
      lng: -72.4,
      img: "https://example.com/itata-heritage.jpg",
      score: 7.8,
      slug: "itata-heritage",
    },
    {
      id: 14,
      name: "Aconcagua Peaks",
      description: "Viñedo andino con noches frías.",
      location: "Valle del Aconcagua, Chile",
      lat: -32.8335,
      lng: -70.5983,
      img: "https://example.com/aconcagua-peaks.jpg",
      score: 8.1,
      slug: "aconcagua-peaks",
    },
    {
      id: 15,
      name: "Curicó Family Vineyard",
      description: "Proyecto familiar con enoturismo.",
      location: "Valle de Curicó, Chile",
      lat: -34.9833,
      lng: -71.2333,
      img: "https://example.com/curico-family-vineyard.jpg",
      score: 8.6,
      slug: "curico-family-vineyard",
    },
    {
      id: 16,
      name: "Bío-Bío Breeze",
      description: "Vinos frescos de clima austral.",
      location: "Valle del Bío-Bío, Chile",
      lat: -36.8201,
      lng: -73.0444,
      img: "https://example.com/biobio-breeze.jpg",
      score: 7.9,
      slug: "bio-bio-breeze",
    },
    {
      id: 17,
      name: "Malleco Origins",
      description: "Viñedos emergentes al sur de Chile.",
      location: "Valle del Malleco, Chile",
      lat: -38.45,
      lng: -72.7167,
      img: "https://example.com/malleco-origins.jpg",
      score: 7.4,
      slug: "malleco-origins",
    },
    {
      id: 18,
      name: "Limarí Coast",
      description: "Brisas marinas que moderan la acidez.",
      location: "Valle del Limarí, Chile",
      lat: -30.5983,
      lng: -71.199,
      img: "https://example.com/limari-coast.jpg",
      score: 8.2,
      slug: "limari-coast",
    },
    {
      id: 19,
      name: "Osorno Mist",
      description: "Viñedos fríos cercanos a volcanes del sur.",
      location: "Provincia de Osorno, Chile",
      lat: -40.571,
      lng: -73.135,
      img: "https://example.com/osorno-mist.jpg",
      score: 7.6,
      slug: "osorno-mist",
    },
    {
      id: 20,
      name: "Valley View Vineyard",
      description: "A vineyard offering breathtaking valley views.",
      location: "Napa Valley",
      lat: 38.5025,
      lng: -122.2654,
      img: "https://example.com/valley-view-vineyard.jpg",
      score: 9.3,
      slug: "valley-view-vineyard",
    },
    {
      id: 21,
      name: "Hillside Vineyard",
      description: "A vineyard situated on picturesque hillsides.",
      location: "Tuscany",
      lat: 43.7711,
      lng: 11.2486,
      img: "https://example.com/hillside-vineyard.jpg",
      score: 8.8,
      slug: "hillside-vineyard",
    },
  ];
};
