export const config = {
  API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL,
  API_KEY: process.env.EXPO_PUBLIC_WINETURE_API_KEY,

  KEYCLOAK_BASE_URL: process.env.EXPO_PUBLIC_KEYCLOAK_BASE_URL,
  KEYCLOAK_ID: process.env.EXPO_PUBLIC_KEYCLOAK_ID,
  KEYCLOAK_SECRET: process.env.EXPO_PUBLIC_KEYCLOAK_SECRET,
  KEYCLOAK_ISSUER: process.env.EXPO_PUBLIC_KEYCLOAK_ISSUER,
  KEYCLOAK_REDIRECT_URI: process.env.EXPO_PUBLIC_KEYCLOAK_REDIRECT_URI,
};
